export interface CardsProps {
  image: string;
  title: string;
  articles: string[];
  agenda: string;
}

export const CardsFields: CardsProps[] = [
  {
    image: "/image/fibromialgia.png",
    title: "Dores no corpo. ",
    articles: [
      "Limitações na funcionalidade.",
      "Dificuldades no estudos.",
      "Alterações emocionais.",
      "Distúrbios do sono.",
      "pior desempenho no trabalho.",
      "Limitações funcionais.",
      "Uso excessivo de medicamentos.",
      "Impacto na saúde mental.",
      "Comprometimento emocional e relacional.",
      "Isolamento social.",
    ],
    agenda: "Agende um Horário",
  },
  {
    image: "/image/estresse e Ansiedade.png",
    title: "Estresse e Ansiedade ",
    articles: [
      "Doenças Cardiovasculares.",
      "Distúrbios Digestivos.",
      "Problemas Imunológicos.",
      "Dores Musculares e Tensão.",
      "Redução do Foco e Concentração.",
      "Conflitos Relacionais.",
      "Qualidade de Vida Geral.",
      "Insônia e Distúrbios do Sono.",
      "Diminuição do Bem-Estar Geral.",
      "Uso Excessivo de Substâncias.",
    ],
    agenda: "Agende um Horário",
  },
  {
    image: "/image/recuperacao_de_Lesoes.png",
    title: "Recuperação de Lesões",
    articles: [
      "Dor e desconforto.",
      "Inflamação. ",
      "Debilidade Muscular. ",
      "Perda de Função. ",
      "Limitações de Mobilidade. ",
      "Autoestima reduzida. ",
      "Cicatrizes e Aderências. ",
      "Limitações funcionais. ",
      "Cicatrizes e Aderências. ",
      "Complicações a Longo Prazo. ",
    ],
    agenda: "Agende um Horário",
  },
  {
    image: "/image/depressao3.png",
    title: "Depressão, Traumas e Transtornos",
    articles: [
      "Sofrimento emocional.",
      "Isolamento social.",
      "Dificuldades no trabalho e estudos. ",
      "Prejuízos nas relações interpessoais. ",
      "Problemas físicos. ",
      "Autoestima reduzida. ",
      "ArtigComportamentos de risco.",
      "Limitações funcionais. ",
      "Custo financeiro. ",
      "Efeitos sobre a saúde física. ",
    ],
    agenda: "Agende um Horário",
  },
  {
    image: "/image/circulacao_sanguinea.png",
    title: "circulação sanguínea ",
    articles: [
      "Dor desconforto nas extremidades.",
      "Pele pálida ou azulada. ",
      "Inchaço. ",
      "Formigamento ou dormência. ",
      "Úlceras de pernas. ",
      "Pernas cansadas ou pesadas. ",
      "Diminuição temperatura nas extremidades. ",
      "Pulsação fraca. ",
      "Dor no peito. ",
      "Disfunção erétil. ",
    ],
    agenda: "Agende um Horário",
  },
  {
    image: "/image/Flexibilidade e Amplitude de Movimento.png",
    title: "Recuperação dos movimentos",
    articles: [
      "Acidente Vascular Cerebral (AVC).",
      "Esclerose Múltipla (EM).",
      "Lesão Medular. ",
      "Doença de Parkinson. ",
      "Esclerose Lateral Amiotrófica (ELA). ",
      "Paralisia Cerebral. ",
      "Lesões Nervosas Periféricas. ",
      "Miastenia Gravis. ",
      "Distúrbios Musculares Hereditários. ",
      "Doença de Lou Gehrig. ",
    ],
    agenda: "Agende um Horário",
  },
  {
    image: "/image/desenvolvimento Pessoal.png",
    title: "Crescimento pessoal",
    articles: [
      "Medo do Fracasso.",
      "Falta de Autodisciplina. ",
      "Falta de Recursos. ",
      "Ambiente Social não adequado. ",
      "Saúde Mental. ",
      "Compromissos Externos. ",
      "Expectativas Externas. ",
      "Falta de Clareza. ",
      "Zona de Conforto.",
      "Crenças Limitantes. ",
    ],
    agenda: "Agende um Horário",
  },
];
